spring:
  datasource:
    dynamic:
      primary: dga #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        dga:
          url: jdbc:mysql://localhost:3306/gmall?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          username: root
          password: "password"
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid:
            initial-size: 5
            max-active: 20
            max-wait: 60000
            min-idle: 5
            test-on-borrow: true
            test-on-return: false
            test-while-idle: true
        mybatis:
          url: jdbc:mysql://localhost:3306/Mybatis?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          username: root
          password: "password"
          driver-class-name: com.mysql.cj.jdbc.Driver
  rsocket:
    server:
      port: 80
#设定自动映射行为 ：FULL标识对象存在嵌套的情况




mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    auto-mapping-behavior=FULL:
    mapUnderscoreToCamelCase: true
logging:
  level:
    com:
      atguigu:
        springbootdemo:
          mapper: debug
hive:
  metastore:
    uris: thrift://hadoop102:9083
